### ISSUE TITLE
SVG are not displayed in Android but correctly in iOS

### ISSUE THREAD

**Issue by phenric** [SergeyMell/nativescript-plugins#17]
Hello Github!

Thanks for this plugin!

In {N}7, the SVG are not displayed in Android. The iOS version is doing fine.

I dropped the SVG files in `/App_Resources/iOS/` and `/App_Resources/Android/src/main/res/`
and the calls to those files are done like that:

`<SVGImage src="res://path"></SVGImage>`

I also added this line `{ from: '**/*.svg', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } }` in webpack.config.js.

Is there an additional config in Android that I miss?

**Comment by SergeyMell** [comment]
If you are using resources for your svg files try to add them to `drawable-nodpi` folder of the `/App_Resources/Android/src/main/res/` directory.
However, there is no need to use resources since you can simply use assets (actually webpack configuration tweaking is required exactly for copying svg from the assets folder)

**Comment by phenric** [comment]
Thx it perfectly works!
